version: "3"

networks:
  syslog-net:
    driver: bridge

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: rijo
      MYSQL_PASSWORD: rijo123
    networks:
      - syslog-net

  syslog:
    build: .
    ports:
      - 5555:8082
    networks:
      - syslog-net
    depends_on:
      - mysql

