version: "3"

networks:
  syslog-net:
    driver: bridge

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: syslog
    networks:
      - syslog-net

  syslog:
    build: .
    ports:
      - 34000:8082
    networks:
      - syslog-net
    depends_on:
      - mysql

